---
easy_admin:
  design:
    menu:
      - icon: home
        label: "Back to the website"
        route: homepage
      - entity: Conference
        icon: map-marker
        label: Conferences
      - entity: Comment
        icon: comments
        label: Comments
  entities:
    Comment:
      class: App\Entity\Comment
      edit:
        fields:
          - property: conference
          - property: createdAt
            type: datetime
            type_options:
              attr:
                readonly: true
          - author
          - property: email
            type: email
          - text
      list:
        fields:
          - author
          - property: email
            type: email
          - property: createdAt
            type: datetime
        filters:
          - conference
        sort:
          - createdAt
          - ASC
    Conference:
      class: App\Entity\Conference
  site_name: "Conference Guestbook"
